# Generated by Django 4.2.3 on 2023-12-22 08:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import facedb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FaceDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=facedb.models.path_and_rename)),
                ('feature', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=128)),
                ('name', models.CharField(max_length=255)),
                ('uniques_id', models.CharField(max_length=255)),
                ('affiliation', models.CharField(max_length=255)),
                ('person_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facedb.persontype')),
            ],
        ),
    ]
