# Generated by Django 4.2.3 on 2023-12-22 09:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facedb', '0002_alter_facedb_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedb',
            name='feature',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=128),
        ),
    ]
