# Generated by Django 4.2.3 on 2023-12-22 08:40

from django.db import migrations, models
import django.db.models.deletion
import fid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facedb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebcamImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='webcam_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_image', models.ImageField(null=True, upload_to=fid.models.path_and_rename)),
                ('manual_checkup', models.BooleanField()),
                ('review', models.BooleanField()),
                ('top1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top1', to='facedb.facedb')),
                ('top2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top2', to='facedb.facedb')),
                ('top3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top3', to='facedb.facedb')),
            ],
        ),
    ]
